# Generated by Django 5.1 on 2024-08-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0002_pokemon_ability_alter_pokemon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image_shiny',
            field=models.URLField(default='Unknown'),
        ),
    ]
